norton_1/app/models/user.py
from datetime import datetime
from werkzeug.security  import generate_password_hash, check_password_hash
from flask_login import UserMixin
from extensions import db
from app.models.associations import user_roles


class User(UserMixin, db.Model):
    __tablename__ = "users"

    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(80), unique=True, nullable=False)
    email = db.Column(db.String(120), unique=True, nullable=False)
    full_name = db.Column(db.String(120), nullable=False)
    is_active = db.Column(db.Boolean, default=True, nullable=False)

    password_hash = db.Column(db.String(120), nullable=False)

    created_at = db.Column(db.DateTime, default=datetime.utcnow, nullable=False)
    updated_at = db.Column(db.DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)

    roles = db.relationship("Role", secondary=user_roles, back_populates="users")


    def set_password(self, password: str)-> None:
        self.password_hash = generate_password_hash(password)

    def check_password(self, password: str)-> bool:
        return check_password_hash(self.password_hash, password)

    def __repr__(self) -> str:
        return f"<User {self.username}>"

norton_1/app/forms/user_forms.py
import re
from flask_wtf import FlaskForm
from wtforms import  BooleanField, StringField, PasswordField, SubmitField, SelectField
from wtforms.validators import Email, DataRequired, Length, EqualTo, ValidationError

from app.models import User, Role

from extensions import db


def strong_password(form, field):
    """"Require at least 8 characters, one uppercase letter, one lowercase letter, one number, and one special character."""
    if len(field.data) < 8:
        raise ValidationError("Password must be at least 8 characters long.")

    if not re.search(r'[A-Z]', field.data):
        raise ValidationError("Password must contain at least one uppercase letter.")

    if not re.search(r'[a-z]', field.data):
        raise ValidationError("Password must contain at least one lowercase letter.")

    if not re.search(r'[0-9]', field.data):
        raise ValidationError("Password must contain at least one number.")

    if not re.search(r'[!@#$%^&*]', field.data):
        raise ValidationError("Password must contain at least one special character.")
    

def _role_choice():
    """Retur list a (id, name) turple for all rold, order by name."""
    return [
        (role.id, role.name)
        for role in db.session.scalars(
            db.select(Role).order_by(Role.name)
        )
    ]

class UserCreateForm(FlaskForm):
    username = StringField(
        "Username",
        validators=[DataRequired(), Length(min=3, max=20)],
        render_kw={"placeholder": "Enter your username"},
    )
    email = StringField(
        "Email",
        validators=[DataRequired(), Email()],
        render_kw={"placeholder": "Enter your email"},
    )
    full_name = StringField(
        "Full Name",
        validators=[DataRequired(), Length(min=3, max=120)],
        render_kw={"placeholder": "Enter your full name"},
    )
    is_active = BooleanField(
        "Is Active",
        default=True,
    )

    role_id = SelectField(
        "Role ID",
        coerce=int,
        validators=[DataRequired(), Length(min=3, max=120)],
        render_kw={"placeholder": "Select Role"},
    )

    password = PasswordField(
        "Password",
        validators=[DataRequired(), strong_password],
        render_kw={"placeholder": "Enter your password"},
    )
    confirm_password = PasswordField(
        "Confirm Password",
        validators=[DataRequired(), EqualTo("password", message="Passwords must match.")],
        render_kw={"placeholder": "Confirm your password"},
    )
    submit = SubmitField("Save")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.role_id.choices = _role_choice()


    def validate_username(self, field):
        exists = db.session.scalar(
            db.select(User).filter(User.username == field.data)
        )
        if exists:
            raise ValidationError("This username is already taken.")
    
    def validate_email(self, field):
        exists = db.session.scalar(
            db.select(User).filter(User.email == field.data)
        )
        if exists:
            raise ValidationError("This email is already registered.")


class UserEditForm(FlaskForm):
    username = StringField(
        "Username",
        validators=[DataRequired(), Length(min=3, max=80)],
    )
    email = StringField(
        "Email",
        validators=[DataRequired(), Email(), Length(max=120)]
    )
    full_name = StringField(
        "Full name",
        validators=[DataRequired(), Length(min=3, max=120)]
    )

    is_active = BooleanField("Active")

    role_id = SelectField(
        "role_id",
        coerce=int,
        validators=[DataRequired()],
    )

    password = PasswordField(
        "Password",
        validators=[strong_password],
        render_kw={"placeholder": "New strong password (optional)"},
    )

    confirm_password = PasswordField(
        "Confirm Password",
        validators=[EqualTo("password", message="Passwords must match.")],
    )
    submit = SubmitField("Update")

    def __init__(self, original_user: User, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.original_user = original_user
        self.role_id.choices = _role_choice()

        if not self.is_submitted():
            if original_user.roles:
                self.original_user.data = original_user.roles[0].id
            else:
                self.role_id.data = None


    def validate_username(self, field):
        q = db.select(User).filter(User.username == field.data, User.id != self.original_user.id)
        exists = db.session.scalar(q)
        if exists:
            raise ValidationError("This username is already taken.")

    def validate_email(self, field):
        q = db.select(User).filter(User.email == field.data, User.id != self.original_user.id)
        exists = db.session.scalar(q)
        if exists:
            raise ValidationError("This email is already registered")

class ConfirmDeleteForm(FlaskForm):
    submit = SubmitField("Comfirm Delete")
    



        

norton_1/app/routes/user_routes.py
from flask import url_for, Blueprint, render_template, redirect, flash, abort
from app.services.user_service import UserService
from flask_login import login_required
from app.forms.user_forms import UserCreateForm, UserEditForm, ConfirmDeleteForm

user_bp = Blueprint("users", __name__, url_prefix="/users")

@user_bp.route("/")
@login_required
def index():
    users = UserService.get_all()
    return render_template("users/index.html", users = users)

@user_bp.route("/<int:user_id>")
@login_required
def detail(user_id: int):
    user = UserService.get_by_id(user_id)
    if user is None:
        abort(404)

    return render_template("users/detail.html", user=user)

@user_bp.route("/create", methods=["GET", "POST"])
@login_required
def create():
    form = UserCreateForm()
    if form.validate_on_submit():
        data = {
            "username": form.username.data,
            "email": form.email.data ,
            "full_name": form.full_name.data,
            "is_active": form.is_active.data
        }
        password  = form.password.data
        role_id = form.role_id.data or None
        user = UserService.create(data, password, role_id)
        flash(f"User '{user.username}' was created successfully.", "success")
        return redirect(url_for("users.detail", user_id=user.id))
    return render_template("users/create.html", form=form)

@user_bp.route("/<int:user_id>/edit", methods=["GET", "POST"])
@login_required
def edit(user_id: int):
    user = UserService.get_by_id(user_id)
    if user is None :
        abort(404)
    
    form = UserEditForm(original_user=user, obj=user)
    
    if form.validate_on_submit():
        data = {
            "username": form.username.data,
            "email": form.email.data,
            "full_name": form.full_name.data,
            "is_active": form.is_active.data
        }
        password = form.password.data or None
        role_id = form.role_id.data or None
        UserService.update(user, data, password, role_id)
        flash(f"User '{user.username}' was updated succesfully.", "success")
        return redirect(url_for("users.detail", user_id = user.id))
        
    return render_template("users/edit.html", form=form, user=user)

@user_bp.route("/<int:user_id>/delete", methods=["GET"])
@login_required
def delete_confirm(user_id: int):
    user = UserService.get_by_id(user_id)
    if user is None:
        abort(404, "User not found")
    
    form = ConfirmDeleteForm()
    return render_template("users/delete_confirm.html", user=user, form=form)

@user_bp.route("/<int:user_id>/delete", methods=["POST"])
@login_required
def delete(user_id: int):
    user = UserService.get_by_id(user_id)
    if user is None:
        abort(404)
    
    UserService.delete(user)
    flash("User was delete succesfully", "success")
    return redirect(url_for("users.index"))

norton_1/app/templates/users/_form.html
{{ form.hidden_tag() }}

<div class="mb-3">
    {{ form.username.label(class="form-label") }}
    {{ form.username(class="form-control") }}
    {% if form.username.errors %}
    <div class="text-danger small">
        {% for error in form.username.errors %}
        <div>{{ error }}</div>
        {% endfor %}
    </div>
    {% endif %}
</div>

<div class="mb-3">
    {{ form.email.label(class="form-label") }}
    {{ form.email(class="form-control") }}
    {% if form.email.errors %}
    <div class="text-danger small">
        {% for error in form.email.errors %}
        <div>{{ error }}</div>
        {% endfor %}
    </div>
    {% endif %}
</div>

<div class="mb-3">
    {{ form.full_name.label(class="form-label") }}
    {{ form.full_name(class="form-control") }}
    {% if form.full_name.errors %}
    <div class="text-danger small">
        {% for error in form.full_name.errors %}
        <div>{{ error }}</div>
        {% endfor %}
    </div>
    {% endif %}
</div>

<div class="form-check mb-3">
    {{ form.is_active(class="form-check-input") }}
    {{ form.is_active.label(class="form-check-label ms-2") }}
</div>

<!-- Role for user input-->
<div class="mb-3">
    {{ form.role_id.label(class="form-label") }}
    {{ form.role_id(class="form-select") }}
    {% if form.role_id.errors %}
    <div class="text-danger small">
        {% for error in form.role_id.errors %}
        <div>{{ error }}</div>
        {% endfor %}
    </div>
    {% endif %}
</div>

<!-- password input -->
<div class="mb-3">
    {{ form.password.label(class="form-label") }}
    {{ form.password(class="form-control") }}
    {% if form.password.errors %}
    <div class="text-danger small">
        {% for error in form.password.errors %}
        <div>{{ error }}</div>
        {% endfor %}
    </div>
    {% endif %}
</div>

<!-- confirm password -->
<div class="mb-3">
    {{ form.confirm_password.label(class="form-label") }}
    {{ form.confirm_password(class="form-control") }}
    {% if form.confirm_password.errors %}
    <div class="text-danger small">
        {% for error in form.confirm_password.errors %}
        <div>{{ error }}</div>
        {% endfor %}
    </div>
    {% endif %}
</div>

<div class="mt-4">
    {{ form.submit(class="btn btn-primary") }}
    <a href="{{ url_for('users.index') }}" class="btn btn-outline-secondary">
        Cancel
    </a>
</div>

norton_1/app/templates/users/delete_confirm.html
{% extends "layouts/base.html" %}
{% block title %}Delete User{% endblock %}

{% block content %}

<div class="card shadow-sm">
    <div class="card-body">
        <h3 class="h4 text-danger">Confirm Delete</h3>

        <p class="mt-3">Are you sure you want to delete the following user</p>

        <ul class="list-group mb-3">
            <li class="list-group-item"><strong>Username:</strong> {{ user.username }} </li>
            <li class="list-group-item"><strong>Full Name:</strong> {{ user.full_name }} </li>
            <li class="list-group-item"><strong>Email:</strong> {{ user.email }} </li>
        </ul>

        <form method="post" action="{{ url_for('users.delete', user_id=user.id) }}">
            {{ form.hidden_tag() }}
            {{ form.submit(class="btn btn-danger") }}
            <a href="{{ url_for('users.index') }}" class="btn btn-secondary">Cancel</a>
        </form>
    </div>
</div>
{% endblock %}

norton_1/app/templates/users/detail.html
{% extends "layouts/base.html" %}
{% block title %} User {{ user.username }} {% endblock %}

{% block content %}
<div class="d-flex justify-content-between align-items-center mb-3">
    <h1 class="h3 mb-0">User Detail</h1>
    <div>
        <a href="{{ url_for('users.edit', user_id=user.id) }}" class="btn btn-sm btn-outline-secondary">Edit</a>
        <a href="{{ url_for('users.index') }}" class="btn btn-sm btn-outline-primary">Back to list</a>
    </div>
</div>

<dl class="row">
    <dt class="col-sm-3">Username</dt>
    <dd class="col-sm-9">{{ user.username }}</dd>

    <dt class="col-sm-3">Emial</dt>
    <dd class="col-sm-9">{{ user.email }}</dd>

    <dt class="col-sm-3">Status</dt>
    <dd class="col-sm-9">
        {% if user.is_active %}
        <span class="badge text-bg-success">Active</span>
        {% else %}
        <span class="badge text-bg-secodary">Inactive</span>
        {% endif %}
    </dd>

    <dt class="col-sm-3">Create at</dt>
    <dd class="col-sm-9">{{ user.created_at }}</dd>

    <dt class="col-sm-3">Last Updated</dt>
    <dd class="col-sm-9">{{ user.updated_at }}</dd>
</dl>

{% endblock %}

norton_1/app/templates/users/index.html
{% extends "layouts/base.html" %}
{% block title %}Users -User Management{% endblock %}

{% block content %}

<div class="d-flex justify-content-between align-items-center mb-4">
    <h1 class="h3 mb-0">User</h1>
    <a href="{{ url_for('users.create') }}" class="btn btn-primary">New User</a>
</div>

{% if users %}
    <div class="table-responsive">
        <table class="table table-striped table-bordered align-middle shadow-sm">
            <thead class="table-light">
                <tr>
                    <th style="width: 50px;">#</th>
                    <th>Username</th>
                    <th>Full Name</th>
                    <th>Email</th>
                    <th>Status</th>
                    <th>Created</th>
                    <th class="text-end" style="width: 160px;">Active</th>
                </tr>
            </thead>
            <tbody>
                {% for user in users %}
                <tr>
                    <td>{{ loop.index }}</td>

                    <td>
                        <a href="{{ url_for('users.detail', user_id=user.id) }}"
                           class="text-decoration-none fw-semibold"
                        >
                            {{ user.username }}
                        </a>
                    </td>

                    <td>{{ user.full_name }}</td>
                    <td>{{ user.email }}</td>

                    <td>
                        {% if user.is_active %}
                        <span class="badge bg-success">Active</span>
                        {% else %}
                        <span class="badge bg-danger">Inactive</span>
                        {% endif %}
                    </td>

                    <td>{{ user.created_at.strftime('%Y-%m-%d') }}</td>

                    <td class="text-end">
                        <a href="{{ url_for('users.edit', user_id=user.id) }}"
                        class="btn btn-sm btn-outline-secondary"
                        title="Edit"
                        >
                        ✏️
                        </a>

                        <a href="{{ url_for('users.delete_confirm', user_id=user.id) }}"
                        class="btn btn-sm btn-outline-danger"
                        title="Delete"
                        >
                        🗑️
                        </a>
                    </td>  
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% else %}
<div class="alert alert-info">
    No users found
    <a href="{{ url_for('users.create') }}">Create the first user</a>
</div>
{% endif %}
{% endblock %}