norton_1/app/models/permission.py
from app.models.associations import role_permissions
from extensions import db
from datetime import datetime


class Permission(db.Model):
    __tablename__ = "permissions"

    id = db.Column(db.Integer, primary_key=True)
    code = db.Column(db.String(64), unique=True, nullable=False, index=True)
    name = db.Column(db.String(120), unique=True, nullable=False, index=True)
    description = db.Column(db.String(255))
    module = db.Column(db.String(80), nullable=False, default="General")
    created_at = db.Column(db.DateTime, default=datetime.utcnow, nullable=False)
    updated_at = db.Column(db.DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)

    roles = db.relationship("Role", secondary=role_permissions, back_populates="permissions")


    def __repr__(self) -> str:
        return f"<Permission {self.code}>"

norton_1/app/forms/permission_forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField, SelectField
from wtforms.validators import DataRequired, ValidationError, Length
from app.models.permission import Permission
from extensions import db

MODULE_CHOICE = [
    ("Users", "Users"),
    ("Roles", "Roles"),
    ("Permission", "Permission"),
    ("System", "System"),
    ("Audit", "Audit"),
    ("General", "General")
]

class PermissionCreateForm(FlaskForm):
    code = StringField(
        "code", 
        validators=[DataRequired(), Length(min=3, max=80)],
        render_kw={"placeholder": "e.g user view"},
    )

    name = StringField(
        "name",
        validators=[DataRequired(), Length(min=3, max=30)],
        render_kw={"placeholder": "Enter your name"},
    )

    module = SelectField(
        "module",
        choices=MODULE_CHOICE,
        default="General",
    )

    description = TextAreaField(
        "description",
        render_kw={"placeholder": "Enter your description"}
    )

    submit = SubmitField("Save")

    def validate_code(self, field):
        exists = db.session.scalar(
            db.select(Permission).filter(Permission.code == field.data)
        )

        if exists:
            raise ValidationError("This permission code is already use.")
        

    def validate_name(self, field):
        exists = db.session.scalar(
            db.select(Permission).filter(Permission.name == field.data)
        )

        if exists:
            raise ValidationError("This permission code is already use.")
        
class PermissionEditForm(FlaskForm):

    code = StringField(
        "code",
        validators=[DataRequired(), Length(min=3, max=80)]
    )

    name = StringField(
        "name",
        validators=[DataRequired(), Length(min=3, max=30)]
    )

    module = SelectField(
        "module",
        choices=MODULE_CHOICE,
        default="General"
    )

    description = TextAreaField("description")

    submit = SubmitField("Save")

    def __init__(self, original_permission: Permission, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.original_permission = original_permission
        
        if not self.is_submitted():
            self.module.data =  original_permission.module

    def validate_code(self, field):
        q = db.select(Permission).filter(Permission.code == field.data, Permission.id != self.original_role.id)

        exists = db.session.scalar(q)
        if exists:
            raise ValidationError("This permission code is already use.")
        
    def validate_name(self, field):
        q = db.select(Permission).filter(Permission.name == field.data, Permission.id != self.original_permission.id)

        exists = db.session.scalar(q)
        if exists:
            raise ValidationError("This permission code is already use.")
        

class PermissionConfirmDelete(FlaskForm):
    submit = SubmitField("Confirm Delete")

norton_1/app/routes/permission.py
from flask import Blueprint, redirect, render_template, flash,abort, url_for
from flask_login import login_required
from app.services.permission import ServicePermission
from app.forms.permission_forms import PermissionCreateForm, PermissionEditForm, PermissionConfirmDelete


permission_bp = Blueprint("permissions", __name__, url_prefix="/permissions")

@permission_bp.route("/")
@login_required
def index():
    permission = ServicePermission.get_permission()
    return render_template("permissions/index.html", permission=permission)

@permission_bp.route("/<int:permission_id>")
@login_required
def detail(permission_id: int):
    permission = ServicePermission.get_permission_id(permission_id)

    if permission is None:
        abort(404)

    return render_template("permissions/detail.html", permission=permission)

@permission_bp.route("/create", methods=["GET", "POST"])
@login_required
def create():

    form = PermissionCreateForm()

    if form.validate_on_submit():
        data = {
            "code": form.code.data,
            "name": form.name.data,
            "module": form.module.data,
            "description": form.description.data,
        }
    
        permission = ServicePermission.create_permission(data)

        flash(f"Permission '{permission.code}' was created succesfully.", "success")
        return redirect(url_for('permissions.index'))
    return render_template("permissions/create.html", form=form)

@permission_bp.route("/<int:permission_id>/edit", methods=["GET", "POST"])
@login_required
def edit(permission_id: int):
    permission = ServicePermission.get_permission_id(permission_id)

    if permission is None:
        abort(404)
    
    form = PermissionEditForm(original_permission=permission, obj=permission)

    if form.validate_on_submit():
        data = {
            "code": form.code.data,
            "name": form.name.data,
            "module": form.module.data,
            "description": form.description.data,
        }

        ServicePermission.update_permission(permission, data)
        flash(f"Permission '{permission.code}' was updated succesfully.", "succes")
        return redirect(url_for('permissions.detail', permission_id = permission.id))
    
    return render_template("permissions/edit.html", form=form, permission=permission)

@permission_bp.route("/<int:permission_id>/delete_confirm", methods=["GET"])
@login_required
def delete_confirm(permission_id: int):
    permission = ServicePermission.get_permission_id(permission_id)

    if permission is None:
        abort(404)
    
    form = PermissionConfirmDelete()
    return render_template("permissions/delete_confirm.html", form=form, permission=permission)

@permission_bp.route("/<int:permission_id>/delete", methods=["POST"])
@login_required
def delete(permission_id: int):
    permission = ServicePermission.get_permission_id(permission_id)

    if permission is None:
        abort(404)
    
    ServicePermission.delete_permission(permission)
    flash("Permis was deleted succesfully.", "success")
    return redirect(url_for('permissions.index'))

norton_1/app/templates/permissions/_form.html
<form method="post">
    {{ form.hidden_tag() }}

     <div class="mb-3">
        {{ form.code.label(class="form-label") }}
        {{ form.code(class="form-control") }}
        {% for error in form.code.errors %}
        <div class="text-danger small">{{ error }}</div>
        {% endfor %}
     </div>

     <div class="mb-3">
        {{ form.name.label(class="form-label") }}
        {{ form.name(class="form-control") }}
        {% for error in form.name.errors %}
        <div class="text-danger small">{{ error }}</div>
        {% endfor %}
     </div>

     <div class="mb-3">
        {{ form.module.label(class="form-label") }}
        {{ form.module(class="form-control") }}
        {% for error in form.module.errors %}
        <div class="text-danger small">{{ error }}</div>
        {% endfor %}
     </div>

     <div class="mb-3">
        {{ form.description.label(class="form-label") }}
        {{ form.description(class="form-control", rows=3) }}
     </div>

     <div class="d-flex justify-content-between mt-3">
        {{ form.submit(class="btn btn-primary") }}
        <a href="{{ url_for('permissions.index')}}" class="btn btn-secondary">Cancel</a>
     </div>
     
</form>

norton_1/app/templates/permissions/create.html
{% extends "layouts/base.html" %}
{% block title %}Create Permission{% endblock %}

{% block content %}
    <h1 class="h3 mb-3">Create Permission</h1>
    {% include "permissions/_form.html" %}
{% endblock %}

norton_1/app/templates/permissions/delete_confirm.html
{% extends "layouts/base.html" %}
{% block title %}Delete Confirm{% endblock %}

{% block content %}
<div class="row justify-content-center">
    <div class="col-md-6">
        <div class="card border-danger">
            <div class="card-header bg-danger text-white">
                <h5 class="mb-0">Confirm Delete</h5>
            </div>
            <div class="card-body">
                <p>
                    Are you sure you want to delete role
                    <strong>{{ permission.code }}</strong> ({{ permission.name }})?
                </p>

                <form method="post">
                    {{ form.hidden_tag() }}

                    <button type="submit" class="btn btn-danger">Delete</button>
                    <a href="{{ url_for('permissions.detail', permission_id=permission_id)}}" class="btn btn-secondary">
                        Cancel
                    </a>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

norton_1/app/templates/permissions/detail.html
{% extends "layouts/base.html" %}
{% block title %}Permissions Detail{% endblock %}

{% block content %}
<div class="d-flex justify-content-between align-items-center mb-3">
    <h1 class="h3 mb-0">Permission:{{ permission.code }}</h1>

    <div>
        <a href="{{ url_for('permissions.edit', permission_id=permission.id)}}" class="btn btn-warning">Edit</a>
        <a href="{{ url_for('permissions.delete_confirm', permission_id=permission.id)}}" class="btn btn-danger">Delete</a>
        <a href="{{ url_for('permissions.index')}}" class="btn btn-secodary">Back</a>
    </div>
</div>

<div class="card">
    <div class="card-body">
        <p><strong>Code:</strong>{{ permission.code }}</p>            
        <p><strong>Name:</strong>{{ permission.name }}</p>            
        <p><strong>Module:</strong>{{ permission.module }}</p>            
        <p><strong>Description:</strong>{{ permission.description or "-" }}</p>
    </div>
</div>
{% endblock %}

norton_1/app/templates/permissions/edit.html
{% extends "layouts/base.html" %}
{% block title %}Edit Permission{% endblock %}

{% block content %}
    <h1 class="h3 mb-3">Edit Permission:{{ permission.code }}</h1>
    {% include "permissions/_form.html" %}

{% endblock %}

norton_1/app/templates/permissions/index.html
{% extends "layouts/base.html" %}
{% block title %}Permissions{% endblock %}

{% block content %}
<div class="d-flex justify-content-between align-items-center mb-3">
    <h1 class="h3 mb-0">Permission</h1>
    <a href="{{ url_for('permissions.create') }}" class="btn btn-primary">Create Permission</a>
</div>

{% if permissions %}
<table class="table table-striped align-middle">
    <thead>
        <tr>
            <th>Code</th>
            <th>Name</th>
            <th>Module</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        {% for perm in permissions %}
        <tr>
            <td>
                <a href="{{ url_for('permissions.detail', permission_id=perm_id)}}">
                    {{ perm.code }}
                </a>
            </td>
            <td>{{ perm.name }}</td>
            <td>{{ perm.module }}</td>
            <td class="text-end">
                <a href="{{ url_for('permissions.edit', permission_id=perm_id)}}" class="btn btn-warning btm-sm">✍️</a>
                <a href="{{ url_for('permissions.delete_confirm', permission_id=perm_id)}}" class="btn btn-danger btn-sm">🗑️</a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% else %}
<p class="text-muted small">No Permission defined yet.</p>
{% endif %}
{% endblock %}